name: Build And Push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Read Version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version  
      
      - name: Environment Variable
        id: vars
        run: echo "::set-output name=build_date::$(date '+%F %T')"

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          BUILD_VERSION: ${{ steps.version.outputs.content }}
          BUILD_DATE: ${{ steps.vars.outputs.build_date }}
          COMMIT_SHA1: ${{ GITHUB_SHA }}
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          platforms: linux/arm,linux/arm64,linux/386,linux/amd64
          tags: 
            -finab/bark-server:latest
            -finab/bark-server:${{ steps.version.outputs.content }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


      
