name: Build And Push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Tencent Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_DOCKER_USERNAME }}
          password: ${{ secrets.TENCENT_DOCKER_PASSWD }}
      - name: Environment Variable
        id: vars
        run: echo "::set-output name=build_version::$(cat ./version)"
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deploy/Dockerfile
          platforms: linux/amd64
          tags: |
            serverless-image/bark-server:latest
            serverless-image/bark-server:${{ steps.vars.outputs.build_version }}
          push: true
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
